CREATE TABLE nfts (
  id SERIAL PRIMARY KEY, 
  uri VARCHAR NOT NULL, 
  name VARCHAR NOT NULL, 
  price NUMERIC NOT NULL, 
  category VARCHAR NOT NULL, 
  tier VARCHAR NOT NULL, 
  theme VARCHAR NOT NULL, 
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  owner_id INT NOT NULL, 
  CONSTRAINT owner_id FOREIGN KEY (owner_id) REFERENCES users(id) NOT VALID
);
